/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dr_evomodel_substmodel_spectra_SpectraJNIWrapper */

#ifndef _Included_dr_evomodel_substmodel_spectra_SpectraJNIWrapper
#define _Included_dr_evomodel_substmodel_spectra_SpectraJNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dr_evomodel_substmodel_spectra_SpectraJNIWrapper
 * Method:    createInstance
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_dr_evomodel_substmodel_spectra_SpectraJNIWrapper_createInstance
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     dr_evomodel_substmodel_spectra_SpectraJNIWrapper
 * Method:    setMatrix
 * Signature: (I[I[DI)I
 */
JNIEXPORT jint JNICALL Java_dr_evomodel_substmodel_spectra_SpectraJNIWrapper_setMatrix
  (JNIEnv *, jobject, jint, jintArray, jdoubleArray, jint);

/*
 * Class:     dr_evomodel_substmodel_spectra_SpectraJNIWrapper
 * Method:    getEigenVectors
 * Signature: (IID[D[D)I
 */
JNIEXPORT jint JNICALL Java_dr_evomodel_substmodel_spectra_SpectraJNIWrapper_getEigenVectors
  (JNIEnv *, jobject, jint, jint, jdouble, jdoubleArray, jdoubleArray);

/*
 * Class:     dr_evomodel_substmodel_spectra_SpectraJNIWrapper
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dr_evomodel_substmodel_spectra_SpectraJNIWrapper_getVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
